// Equix pixel bases + variant overlays for the mint-page showcase.
// Grids are 24x24 strings: X = ink, S = sage, . = cream.
// 4 bases x 5 variants = 20 rotating artworks.

export type Cell = { x: number; y: number; c: "X" | "S" | "." };
export type Variant = { name: string; cells: Cell[] };

export const BASE_GRIDS: Record<string, string[]> = {
  male: [
    "........................",
    "........XXXXXXXX........",
    ".......XXXXXXXXXX.......",
    "......XXXXXXXXXXXX......",
    "......XXXXXXXXXXXX......",
    "......XXX......XXX......",
    "......XX........XX......",
    "......X..XX..XX..X......",
    "......X..SS..SS..X......",
    "......X..........X......",
    "......X....XX....X......",
    ".......X........X.......",
    ".......X..XXXX..X.......",
    ".......XX..XX..XX.......",
    "........X......X........",
    ".........X....X.........",
    "......XXXXX..XXXXX......",
    "....XXXXXXX..XXXXXXX....",
    "...XXXXXXXX..XXXXXXXX...",
    "..XXXXXXXX.SS.XXXXXXXX..",
    "..XXXXXXX..SS..XXXXXXX..",
    "..XXXXXX........XXXXXX..",
    "..XXXXXX........XXXXXX..",
    "........................",
  ],
  female: [
    "........................",
    ".......XXXXXXXXX........",
    "......XXXXXXXXXXX.......",
    ".....XXXXXXXXXXXXX......",
    ".....XXXXXXXXXXXXX......",
    ".....XXX.......XXXX.....",
    ".....XX.........XXX.....",
    ".....XX.XX...XX.XXX.....",
    ".....XX.SS...SS.XXX.....",
    ".....XX.........XXX.....",
    ".....XX....X....XXX.....",
    ".....XXX..XXX..XXXX.....",
    ".....XXX......XXXXX.....",
    ".....XXXX....XXXXXX.....",
    ".....XXXX.SS.XXXXXX.....",
    ".....XXX..SS...XXXX.....",
    ".....XX...XX....XXX.....",
    ".....X.XXXXXXXX..XX.....",
    "....X.XXXXXXXXXX..X.....",
    "....X.XXXXXXXXXX..X.....",
    "......XXXXXXXXXX........",
    "......XXXXXXXXXX........",
    "........................",
    "........................",
  ],
  robot: [
    "...........SS...........",
    "...........XX...........",
    "........................",
    "......XXXXXXXXXXXX......",
    "......XXXXXXXXXXXX......",
    "......XX........XX......",
    "......XX.SSS.SSSXX......",
    "......XX.SSS.SSSXX......",
    "......XX........XX......",
    "......XX.X.X.X..XX......",
    "......XXXXXXXXXXXX......",
    "......XXXXXXXXXXXX......",
    "..........XX............",
    "..........XX............",
    "....XXXXXXXXXXXXXXXX....",
    "...XXXXXXXXXXXXXXXXXX...",
    "...XX...............X...",
    "...XX..S..SSSS..S...X...",
    "...XX...............X...",
    "...XX..XXXX..XXXX...X...",
    "...XXXXXXXXXXXXXXXXXX...",
    "...XXXXXXXXXXXXXXXXXX...",
    "........................",
    "........................",
  ],
  pet: [
    "........................",
    ".....XX..........XX.....",
    "....XXXX........XXXX....",
    "....XXXXX......XXXXX....",
    "....XXXXXXXXXXXXXXXX....",
    "....XXXXXXXXXXXXXXXX....",
    "....XXX..........XXX....",
    "....XX............XX....",
    "....XX.XXX....XX.XXX....",
    "....XX.XSS....SS.XXX....",
    "....XX...........XXX....",
    "....XXX...X..X...XXX....",
    "....XXX....XX....XXX....",
    "....XXXX.X....X.XXXX....",
    ".....XXXXXXXXXXXXXX.....",
    "......XXXXXXXXXXXX......",
    ".........XXXXXX.........",
    "........XXSSSSXX........",
    ".......XXXXXXXXXX.......",
    "......XXXXXXXXXXXX......",
    "......XXXXXXXXXXXX......",
    "........................",
    "........................",
    "........................",
  ],
};

const C = (x: number, y: number, c: "X" | "S" | "."): Cell => ({ x, y, c });
const row = (y: number, x0: number, x1: number, c: "X" | "S" | "."): Cell[] =>
  Array.from({ length: x1 - x0 + 1 }, (_, i) => C(x0 + i, y, c));

export const VARIANTS: Record<string, Variant[]> = {
  male: [
    { name: "CLEAN", cells: [] },
    { name: "SHADES", cells: [...row(7, 8, 16, "X"), ...row(8, 8, 16, "X")] },
    { name: "EARRING", cells: [C(17, 9, "S"), C(17, 10, "S")] },
    { name: "CHAIN GLOW", cells: [C(10, 19, "S"), C(13, 19, "S"), C(10, 20, "S"), C(13, 20, "S")] },
    { name: "SCARLINE", cells: [C(9, 6, "S"), C(10, 7, "S")] },
  ],
  female: [
    { name: "CLEAN", cells: [] },
    { name: "BANGS", cells: [...row(6, 8, 14, "X")] },
    { name: "HOOPS", cells: [C(6, 10, "S"), C(6, 11, "S"), C(16, 10, "S"), C(16, 11, "S")] },
    { name: "SHADES", cells: [...row(7, 8, 15, "X"), ...row(8, 8, 15, "X")] },
    { name: "STAR", cells: [C(15, 5, "S"), C(14, 4, "S"), C(16, 4, "S"), C(15, 3, "S")] },
  ],
  robot: [
    { name: "CLEAN", cells: [] },
    { name: "TWIN ANTENNA", cells: [C(8, 0, "S"), C(8, 1, "X"), C(15, 0, "S"), C(15, 1, "X")] },
    { name: "MONO VISOR", cells: [...row(6, 9, 15, "S"), ...row(7, 9, 15, ".")] },
    { name: "SIDE VENTS", cells: [C(5, 6, "S"), C(5, 7, "S"), C(18, 6, "S"), C(18, 7, "S")] },
    { name: "GLITCH", cells: [C(10, 4, "."), C(12, 4, "."), C(14, 4, ".")] },
  ],
  pet: [
    { name: "CLEAN", cells: [] },
    { name: "FOLDED EAR", cells: [C(18, 1, "."), C(19, 2, "."), C(18, 3, "X")] },
    { name: "PATCH", cells: [...row(8, 13, 16, "X"), ...row(9, 13, 16, "X")] },
    { name: "BELL", cells: [C(11, 18, "S"), C(12, 18, "S")] },
    { name: "WINK", cells: [C(13, 9, "."), C(14, 9, "."), C(13, 10, "S"), C(14, 10, "S")] },
  ],
};

export const SHOWCASE_BASES = ["male", "female", "robot", "pet"] as const;
